# Deep learning knowledge


## python

## numpy

numpy 最核心的概念是数组（ndarray）

1. 数组（ndarray）

- 创建数组

In [ ]:
import numpy as np

# 一维数组（形状(3,)）
arr1 = np.array([1, 2, 3])
print(arr1) # [1 2 3]
print(arr1.shape) # (3,)
print(arr1.ndim) # 1

In [ ]:
# 二维数组（形状(2,3)：2行3列）
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
# [[1 2 3]
#  [4 5 6]]
print(arr2.shape)  # (2, 3)
print(arr2.ndim)  # 2

In [ ]:
# 三维数组（形状(2,2,3)：2个2行3列的矩阵）
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3.shape)  # (2, 2, 3)
print(arr3.ndim)  # 3

- 特殊数组

In [ ]:
np.zeros((2, 3))  # 全0数组，形状(2,3)
# [[0. 0. 0.]
#  [0. 0. 0.]]

np.ones((3,))    # 全1数组，形状(3,)
# [1. 1. 1.]

np.arange(5)     # 类似range，生成0-4的数组
# [0 1 2 3 4]

2. 数组的基本操作

- 索引与切片

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # 形状(3,3)

# 取第2行（索引从0开始）
print(arr[1])  # [4 5 6]

# 取第1行第2列的元素
print(arr[0, 2])  # 3

# 切片：取前2行，前2列
print(arr[:2, :2])
# [[1 2]
#  [4 5]]

- 形状操作

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])  # 形状(6,)

# 改变形状为(2,3)
reshaped = arr.reshape(2, 3)
print(reshaped)
# [[1 2 3]
#  [4 5 6]]
print(reshaped.shape)  # (2, 3)

- 数值运算

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # 对应元素相加：[5 7 9]
print(a * 2)  # 每个元素乘2：[2 4 6]
print(a.mean())  # 平均值：2.0
print(b.sum())   # 求和：15

3. ndarray 属性

- dtype

目标数据类型，可以是 NumPy 类型（如 np.int32、np.float64）、Python 内置类型（如 int、float）等

In [ ]:
arr_int = np.array([1, 2, 3, 4])
print(arr_int.dtype)  # int64（或int32，取决于系统）

- astype

用于将数组的数据类型转换为指定的类型，并返回一个新的数组（原数组不会被修改）。

In [ ]:
arr_float = arr_int.astype(np.float64)
print(arr_float)      # [1. 2. 3. 4.]
print(arr_float.dtype)  # float64

## python

- Optional

Optional[T]，表示可以是指定类型 T，或者是 None

In [ ]:
from typing import Optional

x: Optional[int] = 5
print(x)  # 5
x = None  # 合法
print(x)  # None

- Callable

指可调用对象，格式：Callable[[T1, T2, ...], R]。列表 [T1, T2, ...] 表示可调用对象的参数类型，R 表示可调用对象的返回值类型。

In [ ]:
from typing import Callable

# 定义一个“接受int和str，返回bool”的可调用对象类型
func_type: Callable[[int, str], bool]

def check(x: int, y: str) -> bool:
    return x > 0 and len(y) > 0

func_type = check  # 合法